name: Add to Project

on:
  issues:
    types:
      - opened
      - transferred

  pull_request:
    types:
      - opened

jobs:
  Exec:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: camunda/action-add-to-project@v1
        with:
          project-alias: sre
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
